cities_proper_by_population = {
		'Shanghai': {
						'rank': 1,
						'population': 24256800,
						'definition': 'Municipality',
						'total area': 6340.5,
						'population density': 3826,
						'country': ' China'},
		'Karachi': {
						'rank': 2,
						'population': 23500000,
						'definition': 'Metropolitan Corporation',
						'total area': 3527,
						'population density': 6663,
						'country': ' Pakistan'},
		'Beijing': {
						'rank': 3,
						'population': 21516000,
						'definition': 'Municipality',
						'total area': 16410.54,
						'population density': 1311,
						'country': ' China'},
		'Delhi': {
						'rank': 4,
						'population': 16787941,
						'definition': 'Union territory',
						'total area': 1484,
						'population density': 11313,
						'country': ' India'},
		'Lagos': {
						'rank': 5,
						'population': 16060303,
						'definition': 'Metropolitan City',
						'total area': 1171.28,
						'population density': 13712,
						'country': ' Nigeria'},
		'Tianjin': {
						'rank': 6,
						'population': 15200000,
						'definition': 'Municipality',
						'total area': 11760,
						'population density': 1293,
						'country': ' China'},
		'Istanbul': {
						'rank': 7,
						'population': 14160467,
						'definition': 'Metropolitan Municipality',
						'total area': 5461,
						'population density': 2593,
						'country': ' Turkey'},
		'Tokyo': {
						'rank': 8,
						'population': 13513734,
						'definition': 'Metropolis',
						'total area': 2191,
						'population density': 6168,
						'country': ' Japan'},
		'Guangzhou': {
						'rank': 9,
						'population': 13080500,
						'definition': 'Sub-provincial City',
						'total area': 7434.4,
						'population density': 1759,
						'country': ' China'},
		'Mumbai': {
						'rank': 10,
						'population': 12442373,
						'definition': 'Municipal Corporation',
						'total area': 603.4,
						'population density': 20680,
						'country': ' India'},
		'Moscow': {
						'rank': 11,
						'population': 12380664,
						'definition': 'Federal City',
						'total area': 2510.12,
						'population density': 4859,
						'country': ' Russia'},
		'São Paulo': {
						'rank': 12,
						'population': 12038175,
						'definition': 'Municipality City',
						'total area': 1521.11,
						'population density': 7914,
						'country': ' Brazil'},
		'Shenzhen': {
						'rank': 13,
						'population': 10467400,
						'definition': 'Sub-provincial City',
						'total area': 1991.64,
						'population density': 5256,
						'country': ' China'},
		'Jakarta': {
						'rank': 14,
						'population': 10075310,
						'definition': 'Capital Region – Five Kota',
						'total area': 664.12,
						'population density': 15171,
						'country': ' Indonesia'},
		'Lahore': {
						'rank': 15,
						'population': 10052000,
						'definition': 'City District',
						'total area': 1772,
						'population density': 5673,
						'country': ' Pakistan'},
		'Seoul': {
						'rank': 16,
						'population': 9995784,
						'definition': 'Special City',
						'total area': 605.21,
						'population density': 17134,
						'country': ' South Korea'},
		'Wuhan': {
						'rank': 17,
						'population': 9785392,
						'definition': 'Sub-provincial City',
						'total area': 1327.61,
						'population density': 5187,
						'country': ' China'},
		'Kinshasa': {
						'rank': 18,
						'population': 9735000,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 1117.62,
						'population density': 8710,
						'country': ' Democratic Republic of the Congo'},
		'Cairo': {
						'rank': 19,
						'population': 9278441,
						'definition': 'Governorate',
						'total area': 3085.1,
						'population density': 3008,
						'country': ' Egypt'},
		'Mexico City': {
						'rank': 20,
						'population': 8874724,
						'definition': 'Federal District',
						'total area': 1485.49,
						'population density': 5974,
						'country': ' Mexico'},
		'Lima': {
						'rank': 21,
						'population': 8693387,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 2672.3,
						'population density': 3253,
						'country': ' Peru'},
		'London': {
						'rank': 22,
						'population': 8673713,
						'definition': 'Greater London Authority',
						'total area': 1572.15,
						'population density': 5431,
						'country': ' United Kingdom'},
		'New York City': {
						'rank': 23,
						'population': 8550405,
						'definition': 'City',
						'total area': 783.84,
						'population density': 10908,
						'country': ' United States'},
		'Bengaluru': {
						'rank': 24,
						'population': 8443675,
						'definition': 'Municipal Corporation',
						'total area': 741,
						'population density': 11876,
						'country': ' India'},
		'Bangkok': {
						'rank': 25,
						'population': 8280925,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 1568.74,
						'population density': 5279,
						'country': ' Thailand'},
		'Ho Chi Minh City': {
						'rank': 26,
						'population': 8224400,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 2095.5,
						'population density': 3925,
						'country': ' Vietnam'},
		'Dongguan': {
						'rank': 27,
						'population': 8220207,
						'definition': 'Prefecture-level City',
						'total area': 2469.4,
						'population density': 3329,
						'country': ' China'},
		'Chongqing': {
						'rank': 28,
						'population': 8189800,
						'definition': 'Central Chongqing Municipality',
						'total area': 5473,
						'population density': 1496,
						'country': 'China'},
		'Nanjing': {
						'rank': 29,
						'population': 8187828,
						'definition': 'Sub-provincial City',
						'total area': 4713.85,
						'population density': 1737,
						'country': ' China'},
		'Tehran': {
						'rank': 30,
						'population': 8154051,
						'definition': 'City Municipality',
						'total area': 450.93,
						'population density': 18083,
						'country': ' Iran'},
		'Shenyang': {
						'rank': 31,
						'population': 8106171,
						'definition': 'Sub-provincial City',
						'total area': 12942,
						'population density': 626,
						'country': ' China'},
		'Bogotá': {
						'rank': 32,
						'population': 7776845,
						'definition': 'Capital District',
						'total area': 859.11,
						'population density': 9052,
						'country': ' Colombia'},
		'Ningbo': {
						'rank': 33,
						'population': 7605689,
						'definition': 'Sub-provincial city',
						'total area': 9816.23,
						'population density': 775,
						'country': ' China'},
		'Hong Kong': {
						'rank': 34,
						'population': 7298600,
						'definition': 'Special Administrative Region',
						'total area': 1104.43,
						'population density': 6608,
						'country': ' China'},
		'Hanoi': {
						'rank': 35,
						'population': 7232700,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 3324.5,
						'population density': 2176,
						'country': ' Vietnam'},
		'Baghdad': {
						'rank': 36,
						'population': 7180889,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 4555,
						'population density': 1576,
						'country': ' Iraq'},
		'Changsha': {
						'rank': 37,
						'population': 7044118,
						'definition': 'Prefecture-level City',
						'total area': 11819,
						'population density': 596,
						'country': ' China'},
		'Dhaka': {
						'rank': 38,
						'population': 6970105,
						'definition': 'City Corporation',
						'total area': 300,
						'population density': 56567,
						'country': ' Bangladesh'},
		'Hyderabad': {
						'rank': 39,
						'population': 6731790,
						'definition': 'Municipal Corporation',
						'total area': 621.48,
						'population density': 10832,
						'country': ' India'},
		'Chennai': {
						'rank': 40,
						'population': 6727000,
						'definition': 'Municipal Corporation',
						'total area': 426.51,
						'population density': 15772,
						'country': ' India'},
		'Rio de Janeiro': {
						'rank': 41,
						'population': 6498837,
						'definition': 'Municipality City',
						'total area': 1200.27,
						'population density': 5414,
						'country': ' Brazil'},
		'Faisalabad': {
						'rank': 42,
						'population': 6418745,
						'definition': 'City District',
						'total area': 214,
						'population density': 29907,
						'country': ' Pakistan'},
		'Foshan': {
						'rank': 43,
						'population': 6151622,
						'definition': 'Prefecture-level City',
						'total area': 2034.62,
						'population density': 3023,
						'country': ' China'},
		'Zunyi': {
						'rank': 44,
						'population': 6127009,
						'definition': 'Prefecture-level city',
						'total area': 30763,
						'population density': 199,
						'country': ' China'},
		'Santiago': {
						'rank': 45,
						'population': 5743719,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 1249.9,
						'population density': 4595,
						'country': ' Chile'},
		'Riyadh': {
						'rank': 46,
						'population': 5676621,
						'definition': 'Municipality City',
						'total area': 1233.98,
						'population density': 4600,
						'country': ' Saudi Arabia'},
		'Ahmedabad': {
						'rank': 47,
						'population': 5570585,
						'definition': 'Municipal Corporation',
						'total area': 475,
						'population density': 11728,
						'country': ' India'},
		'Singapore': {
						'rank': 48,
						'population': 5535000,
						'definition': 'City State',
						'total area': 719.1,
						'population density': 7697,
						'country': ' Singapore'},
		'Shantou': {
						'rank': 49,
						'population': 5391028,
						'definition': 'Prefecture-level City',
						'total area': 2064.42,
						'population density': 2611,
						'country': ' China'},
		'Saint Petersburg': {
						'rank': 50,
						'population': 5281579,
						'definition': 'Federal City',
						'total area': 1439,
						'population density': 3608,
						'country': ' Russia'},
		'Yangon': {
						'rank': 51,
						'population': 5214000,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 598.75,
						'population density': 8708,
						'country': ' Myanmar'},
		'Abidjan': {
						'rank': 52,
						'population': 4765000,
						'definition': 'Department/City District',
						'total area': 2119,
						'population density': 2249,
						'country': ' Ivory Coast'},
		'Chengdu': {
						'rank': 53,
						'population': 4741929,
						'definition': 'Sub-provincial City',
						'total area': 421,
						'population density': 11263,
						'country': ' China'},
		'Alexandria': {
						'rank': 54,
						'population': 4616625,
						'definition': 'Governorate',
						'total area': 2300,
						'population density': 2007,
						'country': ' Egypt'},
		'Kolkata': {
						'rank': 55,
						'population': 4496694,
						'definition': 'Municipal Corporation',
						'total area': 185,
						'population density': 24306,
						'country': ' India'},
		'Ankara': {
						'rank': 56,
						'population': 4470800,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 1910.92,
						'population density': 2340,
						'country': ' Turkey'},
		"Xi'an": {
						'rank': 57,
						'population': 4467837,
						'definition': 'Sub-provincial City',
						'total area': 832.17,
						'population density': 5369,
						'country': ' China'},
		'Surat': {
						'rank': 58,
						'population': 4462002,
						'definition': 'Municipal Corporation',
						'total area': 326.515,
						'population density': 13666,
						'country': ' India'},
		'Johannesburg': {
						'rank': 59,
						'population': 4434827,
						'definition': 'Municipality City',
						'total area': 1644.98,
						'population density': 2696,
						'country': ' South Africa'},
		'Dar es Salaam': {
						'rank': 60,
						'population': 4364541,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 1631.12,
						'population density': 2676,
						'country': ' Tanzania'},
		'Suzhou': {
						'rank': 61,
						'population': 4327066,
						'definition': 'Prefecture-level City',
						'total area': 1649.72,
						'population density': 2623,
						'country': ' China'},
		'Harbin': {
						'rank': 62,
						'population': 4280701,
						'definition': 'Sub-provincial City',
						'total area': 1718.2,
						'population density': 2491,
						'country': ' China'},
		'Giza': {
						'rank': 63,
						'population': 4239988,
						'definition': 'Governorate',
						'total area': 289.08,
						'population density': 14667,
						'country': ' Egypt'},
		'Zhengzhou': {
						'rank': 64,
						'population': 4122087,
						'definition': 'Sub-provincial City',
						'total area': 1015.66,
						'population density': 4059,
						'country': ' China'},
		'New Taipei City': {
						'rank': 65,
						'population': 3954929,
						'definition': 'Special Municipality',
						'total area': 2052.57,
						'population density': 1927,
						'country': ' Taiwan'},
		'Los Angeles': {
						'rank': 66,
						'population': 3884307,
						'definition': 'Municipality City',
						'total area': 1213.85,
						'population density': 3200,
						'country': ' United States'},
		'Cape Town': {
						'rank': 67,
						'population': 3740026,
						'definition': 'Municipality City',
						'total area': 2444.97,
						'population density': 1530,
						'country': ' South Africa'},
		'Yokohama': {
						'rank': 68,
						'population': 3726167,
						'definition': 'Designated City',
						'total area': 437.49,
						'population density': 8517,
						'country': ' Japan'},
		'Berlin': {
						'rank': 69,
						'population': 3671000,
						'definition': 'City State',
						'total area': 891.75,
						'population density': 4117,
						'country': ' Germany'},
		'Busan': {
						'rank': 70,
						'population': 3590101,
						'definition': 'Metropolitan City',
						'total area': 766.12,
						'population density': 4686,
						'country': ' South Korea'},
		'Hangzhou': {
						'rank': 71,
						'population': 3560391,
						'definition': 'Sub-provincial City',
						'total area': 728.19,
						'population density': 4889,
						'country': ' China'},
		'Xiamen': {
						'rank': 72,
						'population': 3531347,
						'definition': 'Sub-provincial City',
						'total area': 1699,
						'population density': 2078,
						'country': ' China'},
		'Quanzhou': {
						'rank': 73,
						'population': 3520846,
						'definition': 'Prefecture-level City',
						'total area': 1062,
						'population density': 3315,
						'country': ' China'},
		'Rawalpindi': {
						'rank': 74,
						'population': 3510000,
						'definition': 'City District',
						'total area': 127,
						'population density': 27638,
						'country': ' Pakistan'},
		'Jeddah': {
						'rank': 75,
						'population': 3456259,
						'definition': 'Municipality City',
						'total area': 1765,
						'population density': 1958,
						'country': ' Saudi Arabia'},
		'Durban': {
						'rank': 76,
						'population': 3442361,
						'definition': 'Municipality City',
						'total area': 2291.31,
						'population density': 1502,
						'country': ' South Africa'},
		'Hyderabad': {
						'rank': 77,
						'population': 3429471,
						'definition': 'City District',
						'total area': 114,
						'population density': 30083,
						'country': ' Pakistan'},
		'Kabul': {
						'rank': 78,
						'population': 3414100,
						'definition': 'Municipality City',
						'total area': 275,
						'population density': 12415,
						'country': ' Afghanistan'},
		'Casablanca': {
						'rank': 79,
						'population': 3359818,
						'definition': 'Prefecture',
						'total area': 387,
						'population density': 8682,
						'country': ' Morocco'},
		'Hefei': {
						'rank': 80,
						'population': 3352076,
						'definition': 'Prefecture-level City',
						'total area': 838.52,
						'population density': 3998,
						'country': ' China'},
		'Pyongyang': {
						'rank': 81,
						'population': 3255388,
						'definition': 'Direct-controlled Municipality',
						'total area': 2113,
						'population density': 1541,
						'country': ' North Korea'},
		'Madrid': {
						'rank': 82,
						'population': 3207247,
						'definition': 'Municipality City',
						'total area': 605.77,
						'population density': 5294,
						'country': ' Spain'},
		'Peshawar': {
						'rank': 83,
						'population': 3201000,
						'definition': 'Municipal Corporation',
						'total area': 125,
						'population density': 25608,
						'country': ' Pakistan'},
		'Ekurhuleni': {
						'rank': 84,
						'population': 3178470,
						'definition': 'Municipality City',
						'total area': 1975.31,
						'population density': 1609,
						'country': ' South Africa'},
		'Nairobi': {
						'rank': 85,
						'population': 3138369,
						'definition': 'Capital District',
						'total area': 694.9,
						'population density': 4829,
						'country': ' Kenya'},
		'Zhongshan': {
						'rank': 86,
						'population': 3121275,
						'definition': 'Prefecture-level City',
						'total area': 1783.67,
						'population density': 1750,
						'country': ' China'},
		'Pune': {
						'rank': 87,
						'population': 3115431,
						'definition': 'Municipal Corporation',
						'total area': 450.69,
						'population density': 6913,
						'country': ' India'},
		'Addis Ababa': {
						'rank': 88,
						'population': 3103673,
						'definition': 'Metropolitan Municipality-Province',
						'total area': 526.99,
						'population density': 5889,
						'country': ' Ethiopia'},
		'Jaipur': {
						'rank': 89,
						'population': 3073350,
						'definition': 'Municipal Corporation',
						'total area': 485,
						'population density': 6337,
						'country': ' India'},
		'Buenos Aires': {
						'rank': 90,
						'population': 3054300,
						'definition': 'Federal District',
						'total area': 203,
						'population density': 15046,
						'country': ' Argentina'},
		'Wenzhou': {
						'rank': 91,
						'population': 3039439,
						'definition': 'Prefecture-level City',
						'total area': 1187.88,
						'population density': 2559,
						'country': ' China'},

}

print("City name\tRank\tPopulation\tTotal area\tCountry")

for cities in cities_proper_by_population:
    print(cities.title(),"\t",
          cities_proper_by_population[cities]['rank'],"\t",
          cities_proper_by_population[cities]['population'],"\t",
          cities_proper_by_population[cities]['total area'],"\t",
          cities_proper_by_population[cities]['country'])
